language: cpp
compiler:
    - gcc
matrix:
    include:
        - os: linux
          dist: trusty
          sudo: required
          env: DIST=trusty
        - os: osx

branches:
    except:
        - gh-pages

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-6
            - doxygen
            - doxygen-latex

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo ln -s /usr/bin/g++-6 /usr/local/bin/g++; g++ -v; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gcc@6; g++-6 -v; fi

script:
    - make
    - bin/demo_double_gyre

after_success:
    - if [[ "$DIST" == "trusty" ]]; then cd $TRAVIS_BUILD_DIR; chmod +x code_docs.sh; ./code_docs.sh; fi

notifications:
    email: false
