dist: trusty
sudo: require
language: cpp
compiler:
    - gcc
os:
    - linux
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-6
script:
    - sudo ln -s /usr/bin/g++-6 /usr/local/bin/g++
    - g++ -v
    - make
